stateRegister:
  url: "https://reyestr.court.gov.ua/"
  reviewUrl: "https://reyestr.court.gov.ua/Review/"
  pagingInfo:
    itemsPerPage: "1000"

bot:
  botName: "Document Tracker Bot"
  botToken: ${BOT_TOKEN}

spring:

  config:
    import: sec.yml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/doctrackerbot?serverTimezone=Europe/Kiev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
