stateRegister:
  url: "https://reyestr.court.gov.ua/"
  reviewUrl: "https://reyestr.court.gov.ua/Review/"
  pagingInfo:
    itemsPerPage: "1000"

bot:
  botName: "Document Tracker Bot"
  botToken: ${BOT_TOKEN}
  limitDocumentsAtOneMessage: ${LIMIT}
  # every 2 minutes = 0 */2 * * * *
  # every 2 minutes = 0 13 22 * * *
  # every day on 22:02 minutes = 0 3 22 * * *
  # past hour 11, 14, and 17 on every day-of-week from Monday through Friday =
  # 0 0 11,14,17 * * MON-FRI
  synchroniseCron: "0 0 18 * * MON-FRI"
  timezone: "Europe/Kiev"

spring:

  config:
    import: sec.yml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/doctrackerbot?serverTimezone=Europe/Kiev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
