stateRegister:
  url: "https://reyestr.court.gov.ua/"
  reviewUrl: "https://reyestr.court.gov.ua/Review/"
  pagingInfo:
    itemsPerPage: "1000"

bot:
  botName: "Document Tracker Bot"
  botToken: ${BOT_TOKEN}
  limitDocumentsAtOneMessage: 2
  limitDocumentSyncsWithoutUpdate: 40
  # every 2 minutes
  # 0 */2 * * * *
  # past hour 18 on every day-of-week from Monday through Friday =
  # 0 0 18 * * MON-FRI
  synchroniseCron: "0 0 18 * * MON-FRI"
  timezone: "Europe/Kiev"

spring:

  config:
    import: sec.yml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
